# 5.16 LIST 2 DIMENSI
Pada python sistem tidak hanya dapat mengerjakan list 1 dimensi tetapi juga dapat mengerjakan list berupa 2 dimensi. Data 2 dimensi merupakan sebuah data berupa list atau array yang didalamny terdapat list/array yang membentuk list 2 dimensi tersebut. List 2 dimensi ini pada matematik disebut sebagai matriks. Tak hanya matriks, list 2 dimensi biasanya juga digunakan utuk menyimpan struktur data yang kompleks sepert tabel, graph, dsb. 

In [3]:
#LATIHAN 1 

#pada pembuatan list 2 dimensi data yang dapat dimasukkan adalah data homogen berupa integer seperti yang dibawah ini
#pendeklarasian list dapat dilakukan seperti dibawah ini, dimana bentuk ini berupa bentuk matriks pada matematika
bil_bulat = [
    [2,4,24,6,86],
    [1,9,7,33,63],
    [2,4,6,8,10],
    [3,9,15,21,27]
]

#setelah pendeklarasian, jika ingin memerintahkan sistem untuk mencetak data yang telah dimasukkan maka perintah print dapat dimasukkan
print('contoh bilangan bulat:')
print(bil_bulat)

#output yang akan dikerluarkan seperti ini :
#[[2, 4, 24, 6, 86], [1, 9, 7, 33, 63], [2, 4, 6, 8, 10], [3, 9, 15, 21, 27]]

#dapat dilihat diatas data bentuk matriks yang kita masukkan jika diperintahkan untuk dicetak akan berbentik list
#dimana didalam list tersebut terdiri dari beberapa list pembentuk.
#mulai dari list baris pertama hingga list baris keempat.

contoh bilangan bulat:
[[2, 4, 24, 6, 86], [1, 9, 7, 33, 63], [2, 4, 6, 8, 10], [3, 9, 15, 21, 27]]


In [4]:
#LATIHAN 2 

#Jika pada latihan 1 data list yang dimasukkan berupa bilangan atau data bertipe integer
#sekarang saya akan mencoba memasukkan data heterogen berupa integer dan strin yang disatukkan.

angkatan_22 = [
    ["anna","etha","itha","hera"], #perbedaan tanda petik pada data bertipe string tidak akan mempengaruhi kode
    [2,9,6,75],
    ['yuni',5,'deswinta',3],
    [23,90,'galuh',8]             #serta pencampuran 2 tipe data dalam suatu list juga tidak akan mempengaruhi kode
]

#format pendeklarasian data list adalah berupa : 
#nama list 2 dimensi = [ 
#    [list baris ke-1], (jangan lupa penambahan tanda koma pada baris awal hingga baris ke n-1)
#    [list baris ke-2], (penambahan tanda koma disini berarti matriks ini tetap berlanjut hingga baris terakhir)
#    [list baris ke-n]  (tanda koma ini juga memudahkan sistem untuk mencetak data list berupa matriks manjadi data list 2 dimensi)
#]

print("Data mahasiswa angkatan 22 : ")
print(angkatan_22)

#output yang akan dikeluarkan akan berupa string dan juga integer
#jadi dapat disimpulkan bahwa kode list 2 dimensi ini dapat menggunakan bertipe string, data bertipe integer serta data bertipe campuran.

Data mahasiswa angkatan 22 : 
[['anna', 'etha', 'itha', 'hera'], [2, 9, 6, 75], ['yuni', 5, 'deswinta', 3], [23, 90, 'galuh', 8]]


In [5]:
# LATIHAN 3 

#pencetakkan data list juga bisa dilakukan perbaris atau hanya satu list pembentuk yang dicetak. 

#format : nama list 2 dimensi [urutan baris]
print("list dibawah ini merupakan bilangan bulat kelipatan 2 : ")
bil_bulat[2]

#list yang di proses merupakan list yang ada pada latihan 1, karena setelah menjalankan kodenya
#data yang dijalankan akan diingat oleh sistem 
#maka dapat kita perintahkan kembali data yang ada dengan kode perintah yang baru

#output yang dikeluarkan adalah satu list sesuai dengan urutan kode diatas.

list dibawah ini merupakan bilangan bulat kelipatan 2 : 


[2, 4, 6, 8, 10]

In [6]:
#LATIHAN 4 

#Jika pada latihan sebelumnya yang kita cetak adalah satu list pembentuk list 2 dimensi
#namun kali ini yang akan kita cetak adalah salah satu anggota pada list pembetuk list 2 dimensi

print ("salah satu mahasiswa angkatan 22 yang mendapatkan nilai excelent :")

angkatan_22[3][2]
#format penulisan kode : nama list[urutan baris][urutan kolom]

#output yang akan dikeluarkan hanya satu data yang merupakan anggota dari list pembentuk list 2 dimensi
#dan data yang dicetak akan berada pada baris serta kolom yang dimasukkan pada kode perintah pencetakan

salah satu mahasiswa angkatan 22 yang mendapatkan nilai excelent :


'galuh'

In [7]:
#LATIHAN 5

#data yang merupakan anggota list data diganti degan menggunakan kode dibawah ini

#format kode penggantian : nama list[pada baris ke-][pada kolom ke-] = data pengganti
angkatan_22[0][2] = 256

#jika ingin memastikan apakah data telah diganti dapat mencetak data yang telah diganti dengan kode pencetakan satu data
#seperti pada latihan sebelumnya
print('data terbaru : ')
print(angkatan_22[0][2])

print("")  #pencetakan spasi

#setelah itu dapat juga kita cetak list 2 dimensi setelah dilakukannya penggantian data
#hanya dengan memanggil nama listnya maka output yang kita dapatkan berupa bentuk list yang dimsukkan bedanya hanya pada data yang telah diganti
print('list data berupa matris setelah diubah')
angkatan_22     #format pemanggilan : nama list

data terbaru : 
256

list data berupa matris setelah diubah


[['anna', 'etha', 256, 'hera'],
 [2, 9, 6, 75],
 ['yuni', 5, 'deswinta', 3],
 [23, 90, 'galuh', 8]]

In [11]:
#LATIHAN 6 

# pada matriks kita dapat memanggil baris lalu mencetaknya sesuai urutan kebawah.
#pada pemanggilan ini akan menggunakan kode for untuk menjelaskan perintah pada sistem
#atau secara singkat kode dibawah ini berguna untuk menampilkan semua isi dalam list 2 dimensi,
#maka digunakannya perulangan bersarang.


print("penjabaran list pembentuk beserta anggota-anggotanya :")
print("") # pencetakan spasi


for baris in bil_bulat:   # format : for nama list pembentuk in nama list 2 dimensi:
    print(baris)          #              print(nama list pembentuk)
    for kolom in baris:   #              for nama anggota list pembentuk in nama list pembentuk:
        print(kolom)      #                  print (nama anggota list pembentuk)
        
#outut yang akan didapatkan adalah pertama list pembentuk lalu penjabaran anggota anggota list pembentuk
#lalu akan dicetak list pembentuk selanjutnya, begitu seterusnya sehingga  list pembentuk habis.

penjabaran list pembentuk beserta anggota-anggotanya :

[2, 4, 24, 6, 86]
2
4
24
6
86
[1, 9, 7, 33, 63]
1
9
7
33
63
[2, 4, 6, 8, 10]
2
4
6
8
10
[3, 9, 15, 21, 27]
3
9
15
21
27


In [13]:
#LATIHAN 7

#pembuatan list 2 dimensi dapat dilakukan seperti dibawah ini
#namun bedanya jika menggunakan kode ini semua anggota pembentuk list ini adalah anggota yang sama

print("list 2 dimensi dengan anggota yang sama : ")
baris, kolom = (5,5)
list_2_dimensi = [[0]*kolom]*baris
print(list_2_dimensi)

#pada baris pertama kode yang diperintahkan dijelaskan bahwa akan ada 5 anggota pada list pembentuk
#dan ada 5 list pembentuk untuk membentuk list 2 dimensi
#dapat kita lihat bahwa diatas ini dimasukkan anggota (0) dimana anggota ini yang akan membentuk list
# lalu anggota akan dikalikan dengan jumlah anggota list setelah itu akan dikalikan lagi dengan jumlah
#list pembentuknya. 

#maka output yang akan dihasilkan seperti yang dibawah ini:

list 2 dimensi dengan anggota yang sama : 
[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [17]:
#LATIHAN 8

#contoh pada latihan sebelumnya adalah sebuah list yang tebentuk dari anggota yang sama
#itu juga berarti setiap list pembentuknya merupakan list yang sama

print("list 2 dimensi dengan anggota yang sama sebelum diubah : ")
baris, kolom = (5,5)
list_2_dimensi = [[0]*kolom]*baris
print(list_2_dimensi, "sebelum")

#bagaimana jika salah satu anggota pada list pembentuk diganti, disaat semua list pembentuknya merupakan list yang sama
#maka penggantian anggota juga akan terjadi pada semua list pembentuk 
#penggantian dapat menggunakan kode dibawah ini

print ("")   #pencetakan spasi

print("list 2 dimensi dengan anggota yang sama setelah diubah : ")
list_2_dimensi[0][0] = 1
print(list_2_dimensi, 'setelah')

#maka setip anggota (0) dengan urutan ke 0 pada setiap list akan di ganti dengan anggota (1)

list 2 dimensi dengan anggota yang sama sebelum diubah : 
[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]] sebelum

list 2 dimensi dengan anggota yang sama setelah diubah : 
[[1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0]] setelah


# 5.17 TUPLES
Kode tuples kurang lebih sama dalam segi pengoprasiannya dengan kode List hanya saja pada kode truples kita tidak dapat mengganti anggota yang telah dijalankan, sedangkan pada kode list dapat diganti setelah di jalankan.

Kode Tuples dibuat dengan cara menambahkan anggota pada tanda () dan di pisahkan oleh tanda koma(,).

In [29]:
#LATIHAN 1

#Berikut beberapa perintah pencetakan kode tuples untuk beberapa tipe data
#format penulisan kode : nama tuples = (anggota tuples)

#TUPLES TANPA ANGGOTA

tuple_kosong = ()
print("Berikut merupakan tuples dimana tidak adanya anggota :")
print(tuple_kosong)
#kode diatas memerintahkan sistem untuk mencetak sebuah tuples tanpa anggota
#dimana output yang dikeluarkan hanya sebuah tanda kurung tanpa anggota ()


print("")   #pencetakan spasi


#TUPLES DENGAN ANGGOTA BERTIPE INTEGER

tuple_bertipe_integer = (4,8,2,8,5)
print("Berikut tuples yang beranggotakan data bertipe integer :")
print(tuple_bertipe_integer)
#kode ini memerintahkan sistem mencetak data bertipe integer yang dimasukkan
#data tersebut akan dicetak menjadi sebuah tuples dengan urutan yang sesuai.


print("")   #pencetakan spasi


#TUPLES DENGAN TIPE CAMPURAN (INTEGER, FLOAT, STRING)

tuple_bertipe_campuran = (23,"Matematika",56,0.9,'Udayana')
print("Berikut tuples yang beranggotakan data bertipe campuran :")
print(tuple_bertipe_campuran)
#Data yang dapat diinput juga bertipe float dan string dan juga dapat bertipe campuran 


print("")   #pencetakan spasi

#TUPLES BERLAPIS

tuple_berlapis = ("Universitas",[2,8,19],(6,9,20),["Matematika",'FMIPA',"Udayana"])
print("Berikut tuples yang beranggotakan data bertipe campuran :")
print(tuple_berlapis)
#sama seperti list diatas, dimana list dapat berupa 2 dimensi 
#sama seperti itu tuples juga dapat berupa 2 dimensi
#hasil yang dicetak juga tetap sama pada posisi yang diinput.

print("")   #pencetakan spasi

#kode tuples juga dapat langsung dideklarasikan seperti dibawah ini
#kode ini lebih sederhana dan lebih efisiensi, kode ini tida menggunakan () untuk mendeklarasikan anggotanya

tuples = 1,2,3,8,"hera"
print("Tuples dengan kode yang lebih sederhana :")
print(tuples)

#hasil pencetakannya pun tidak ada bedanya dengan yang sebelumnya

Berikut merupakan tuples dimana tidak adanya anggota :
()

Berikut tuples yang beranggotakan data bertipe integer :
(4, 8, 2, 8, 5)

Berikut tuples yang beranggotakan data bertipe campuran :
(23, 'Matematika', 56, 0.9, 'Udayana')

Berikut tuples yang beranggotakan data bertipe campuran :
('Universitas', [2, 8, 19], (6, 9, 20), ['Matematika', 'FMIPA', 'Udayana'])

Tuples dengan kode yang lebih sederhana :
(1, 2, 3, 8, 'hera')


In [33]:
#LATIHAN 2

#pengecekan tipe data pada perintah
#format kode pengecekan : nama data yang ingin dicek = ("data")
#                         print(type(nama data))

tuples_1 = ("Matematika")
print(type(tuples_1))

print("")   #pencetakan spasi

tuples_2 = ("Matematika",)
print(type(tuples_2))

print("")   #pencetakan spasi

tuples_3 = "Matematika",
print(type(tuples_3))

#seperti kode yang telah dijalankan kita dapat mengecek tipe data
#pembedanya tipe str dengan tuple hanya pda tanda koma yang diletakkan setelah anggota data
#tanda (,) berarti masih ada anggota lanjutan pada data tersebut
#jika ada tanda koma berarti data tersebut betipe tuple namun jika tidak ada tanda koma maka berarti data tersebut bertipe str

<class 'str'>

<class 'tuple'>

<class 'tuple'>


In [38]:
#LATIHAN 3 

#Pemanggilan salah satu anggota pada tuple atau biasanya disebut sebagai indexing
#format pemanggilan : print(nama tuple[nomor urutan anggota])

matematika = ("Beta", "Alpha","Kalkulus","Theta","Delta")
#pertama dideklarasikan tuple berserta aggotanya 
#setelah itu dapat dilakukan pemanggilan salah satu anggota

print("Salah satu lambang matematika : ")
print(matematika[3])
#penulisan kode dapat dilakukan seperti yang diatas ini

print("")

#atau dapat juga dilakukan seperti ini
print("Salah satu lambang matematika : ", matematika[3])
 
#output yang akan dikeluarkan berupa anggota yang dipanggil
#perbedaan output dari kedua kode diatas hanya terletak pada pencetakan aggota 
#jika ada tambahan kalimat yang ingin dicetak sebelum anggota dan dicetak secara terpisah dapat menggunakan kode diatas
#namun jika ingi pencetakan secara tersambung maka dapat menggunakan kode dibawah.

Salah satu lambang matematika : 
Theta

Salah satu lambang matematika :  Theta


In [42]:
#Tak hanya pemanggilan dengan urutan biasa namun juga bisa dilakukan dengan pemanggilan dengan urutan min

matematika = ("Beta", "Alpha","Kalkulus","Theta","Delta")
#pertama dideklarasikan tuple berserta aggotanya 
#setelah itu dapat dilakukan pemanggilan salah satu anggota

print("Salah satu matakuliah matematika : ")
print(matematika[-3])
#penulisan kode dapat dilakukan seperti yang diatas ini

print("")

#atau dapat juga dilakukan seperti ini
print("Salah satu matakuliah matematika : ", matematika[-3])
 
#anggota [-3] merupakan anggota ketiga dari akhir yang data tuple yang dimasukkan.

Salah satu matakuliah matematika : 
Kalkulus

Salah satu matakuliah matematika :  Kalkulus


In [47]:
#LATIHAN 4 

#Jika pada latihan sebelumnya hanya satu anggota yang dipanggil 
#pada latihan ini akan ada lebih dari satu anggota yang di panggil
#dapat menggunakan format : print(nama tuple[batas awal:batas akhir])

#pendeklarasian data tuple yg akan diproses
jurusan = "M","A","T","E","M","A","T","I","K","A"

#pemanggilan semua anggota yang diinput pengguna
print('Pemanggilan semua anggota : ')
print(jurusan[:])

#jika tidak ada batas yang dimasukkan maka itu berarti sistem menceetak seluruh anggota
#tetapi jika jika tidak dimasukkan batas awal maka yang dicetak adalah anggota dari awal hingga batas akhir
#begitu juga sebaliknya jika tidak diinput batas akhir.

print("")    #pencetakan spasi

print('pencetakan data dengan batas :')
print(jurusan[2:-1])
#output yang akan dikeluarkan berupa anggota ke 2 hingga anggota terakhir 
#karena -1 berarti anggota pertama dari akhir

print("")    #pencetakan spasi

print('pencetakan data dengan batas :')
print(jurusan[:-4])
#output yang akan dicetak ialah anggota dari awal hingga anggota keempat dari akhir

print("")    #pencetakan spasi

print('pencetakan data dengan batas :')
print(jurusan[3:])
#anggota yang dicetak adalah dari anggota ke 3 hingga anggota terakhir.

#pemanggilan sejumlah anggota diatas ditentukan dari batas awal dan akhir yang diinput oleh pengguna

Pemanggilan semua anggota : 
('M', 'A', 'T', 'E', 'M', 'A', 'T', 'I', 'K', 'A')

pencetakan data dengan batas :
('T', 'E', 'M', 'A', 'T', 'I', 'K')

pencetakan data dengan batas :
('M', 'A', 'T', 'E', 'M', 'A')

pencetakan data dengan batas :
('E', 'M', 'A', 'T', 'I', 'K', 'A')


In [25]:
#LATIHAN 5

#Anggota pada sebuah tuples dimana terdata lebih dari satu anggota yang sama, maka dapat dihitung jumlah anggota yang diinginkan
#menggunakan format : print(nama tuple.count(data yang ingin dihitung))

#Tak hanya anggota tapi kita juga dapat menghitung jumlah seluruh anggota pada sebuah tuple menggunakan kode len
#format kode : print(len(nama tuple))

#pendeklarasian data tuple yg akan diproses
jurusan = "M","A","T","E","M","A","T","I","K","A"


print("Jumlah Anggota Tuple Jurusan : ",  len(jurusan))
#output berupa jumlah seluruh anggota pada sebuah tuple


print("")   #penecetakan spasi


print('Jumlah Anggota "M" pada tuple jurusan : ', jurusan.count('M'))
#outut yang akan dikeluarkan oleh kode ini ialah jumlah anggota yang di panggil pada sebuah tuple yang diinginkan.

print("")   #penecetakan spasi

#jika ingin mengetahui urutan sebuah data pada sebuah tuple dapat menggunakan kode index 
#dengan format : nama tuple.index(anggota)

print("anggota'I' pada tuple ada pada urutan ke : ", jurusan.index("I"))


Jumlah Anggota Tuple Jurusan :  10

Jumlah Anggota "M" pada tuple jurusan :  2

anggota'I' pada tuple ada pada urutan ke :  7


In [12]:
#LATIHAN 6

matematika = ("Beta", "Alpha","Kalkulus","Theta","Delta")
#pertama dideklarasikan tuple berserta aggotanya 

#Format kode untuk mengecek salah satu anggota pada sebuah tuple adalah : print('anggota yg ingin di cek' in nama tuple)
#kode untuk mengecek anggota ini memudahkan pengguna untuk mengecek anggota yang ingin dicari pada sebuah tuple
#tanpa harus mencarinya satu persatu.

print('apakah Kalkulus ada dalam tuple ? ','Kalkulus' in matematika)

print('apakah Aljabar ada dalam tuple ?', 'Aljabar'in matematika)

#output yang akan dikeluarkan adalah 'true' atau 'false'
#jika anggota yang ingin dicek pada sebuat tuple tidak ada didalamnya maka output yang akan dikeluarkan adalah 'false'
#begitupun sebaliknya, jika anggota yang inggin di cek ada maka yang akan dikeluarkan adalah 'true'

apakah Kalkulus ada dalam tuple ?  True
apakah Aljabar ada dalam tuple ? False


In [17]:
#LATIHAN 7 

#pertama dilakukannya pendeklarasian 2 buah tuple yang ingin diproses oleh sistem
matematika = ("Beta", "Alpha","Kalkulus","Theta","Delta")
bil_bulat = (4,8,2,8,5)


#Penggabungan 2 buah tuple menjadi 1 tuple
#format : print(tuple1 + tuple2)

print("2 tuple yang digabung : ")
print(matematika + bil_bulat)

print("")   #print spasi

#Penggabungan 2 tuple menjadi 1 tuple 2 dimensi
#format : tuple3 = (tuple1,tuple2)
#         print(tuple3)

tuple_2_dimensi = (bil_bulat, matematika)
print('tuple 2 dimensi : ')
print(tuple_2_dimensi)

#tuple 2 dimensi tidak hanya dapat dibuat dengan memasukkan beberapa tuple menjadi sebuah bentuk matriks 
#tapi dapat juga dengan menggabungkan 2 atau lebih tuple menjadi sebuah tuple 2 dimensi seperti diatas.


2 tuple yang digabung : 
('Beta', 'Alpha', 'Kalkulus', 'Theta', 'Delta', 4, 8, 2, 8, 5)

tuple 2 dimensi : 
((4, 8, 2, 8, 5), ('Beta', 'Alpha', 'Kalkulus', 'Theta', 'Delta'))


In [19]:
#LATIHAN 8 

#dilakukannya pendeklarasian tuple berserta anggotanya
matematika = ("Beta", "Alpha","Kalkulus","Theta","Delta")
matematika.append("Aljabar")

#seperti definisi tuple dimana tuple merupakan sebuah kumpulan data yang berbentuk list namun tidak dapat diubah setelah dijalankan
#karena definisi diataslah maka kode append, remove, del, ataupun kode penggantian anggota
#ketika dijalankan akan menjadi sebuah eror karena data tuple tida menerima perubahan setelah dijalankan.


AttributeError: 'tuple' object has no attribute 'append'

In [28]:
#LATIHAN 9

#pada latihan kali ini saya akan mencoba mengubah sebuah kalimat menjadi sebuah tuple
#dimana anggota anggota tuplenya merupakan semua huruf pembentuknya beserta spasinya
#dapat menggunakan format : print(tuple(kumpulan data yang ingin diubah menjadi tuple))

print("Tuple baru : ")
print(tuple("ALGORITMA DAN STRUKTUR DATA"))

#outputnya berupa kumpulan anggota yang telah dipisahkan dari satu sama yang lain dan menjadi bagian dari tuplenya.

Tuple baru : 
('A', 'L', 'G', 'O', 'R', 'I', 'T', 'M', 'A', ' ', 'D', 'A', 'N', ' ', 'S', 'T', 'R', 'U', 'K', 'T', 'U', 'R', ' ', 'D', 'A', 'T', 'A')


# 5.18 DICTIONARIES
Dictionaries pada python merupakan kumpulan data data yang menjadi kunci pengoprasian data, dan pada dictionaries dapat menyimpan lebih dari 1 elemen. 

In [31]:
#lATIHAN 1

#pada latihan pertama ini kita akan mencoba membuat sebuah dictionaries
#penulisan dictionaries biasanya menggunakan format : nama dictionaries = {data utama 1: data sekunder 1, data utama 2: data sekunder 2}
#penulisan data mulai dari data pertama hingga data ke n

#data yang merupakan tipe data string diharapkan menggunakan tanda petik, baik data utama maupun data sekunder

integer = {1:"Beta", 2:"Theta", 3:"Delta"}
print("Data dictionaries dimana data utamanya berupa integer : ")
print(integer)
#pada contoh diatas ini data utamanya merupakan data bertipe integer sedangkan data sekundernya merupakan data bertipe string.

print("")    #pencetakan spasi

campuran = {
    "nama" : "hera",
    1 : [22,8,54,10,27]
}
print('Berikut contoh dictionaries campuran : ')
print(campuran)

#sedangkan pada kode kedua ini data utama yang diinput ada 2 tipe yaitu string dan integer
#lalu untuk data sekundernya terdapat 2 yaitu data berupa string dan data berupa list integer
# dimana pada penulisan list menggunakan kurung yang berbeda dari kurung yang digunakan pada dictionaries
#penulisan dictionaries juga dapat ditulis kesamping atau ditulis kebawah tidak ada bedanya pada output yang akan dikeluarkan.

Data dictionaries dimana data utamanya berupa integer : 
{1: 'Beta', 2: 'Theta', 3: 'Delta'}

Berikut contoh dictionaries campuran : 
{'nama': 'hera', 1: [22, 8, 54, 10, 27]}


In [34]:
#LATIHAN 2

kosong = {}
print ('Berikut merupakan contoh dictionaries kosong :')
print(kosong)

#dictionaries kosong merupakan dictionaris tanpa data utama maupun data sekunder.

print("")   #pencetakan spasi

penulisan_2 = dict ({1:"Beta", 2:"Theta", 3:"Delta"})
print('Output dari penulisan kode berbeda pertama : ')
print (penulisan_2)

#tak hanya penulisan seperti pada Latihan 1, penulisan dictionaries dapat juga dituliskan seperti ini
#dimana pada penulisan kali ini menggunakan kode dict sebelum pengiinputan data dan penulisan ini menggunakan ()

print("")   #pencetakan spasi

penulisan_3 = dict ([(1,"Beta"), (2,"Theta"), (3,"Delta")])
print('Output dari penulisan kode berbeda kedua : ')
print (penulisan_3)

#pada penulisan kali ini cukup rumit dimana ada 2 tanda kurung pada data yang diinput 
#lalu untuk membedakan data pertama dan kedua digunakannya tanda kurung lagi
#namun untuk memisahkan data utama dan sekunder menggunakan tanda koma bukan tanda (:)
#dan tetap menggunakan kode dict didepannya

#output yang dikeluarkan tetaplah sama
#jadi adanya perbedaan penulisan ini sesuai denga kenyamanan pengguna untuk menjalankan kode yang dirasa nyaman.

Berikut merupakan contoh dictionaries kosong :
{}

Output dari penulisan kode berbeda pertama : 
{1: 'Beta', 2: 'Theta', 3: 'Delta'}

Output dari penulisan kode berbeda kedua : 
{1: 'Beta', 2: 'Theta', 3: 'Delta'}


In [36]:
#LATIHAN 3

data_2dimensi =  {"Jurusan":"Matematika", "Fakultas":"MIPA","Universitas":"Udayana",
             "Lambang":{1:"Beta", 2:"Theta", 3:"Delta"}}
print("Berikut contoh dictionaries 2 dimensi : ")
print(data_2dimensi)

#jika pada latihan pertama ada data sekunder yang merupakan list
#pada latihan kali ini ada data dictionaries dalam sebuah data dictionaries 
#maka akandihasilkannya data 2 dimensi seperti dibawah ini.


Berikut contoh dictionaries 2 dimensi : 
{'Jurusan': 'Matematika', 'Fakultas': 'MIPA', 'Universitas': 'Udayana', 'Lambang': {1: 'Beta', 2: 'Theta', 3: 'Delta'}}


In [47]:
#LATIHAN 4 

#kode pada dictionaris dapat diubah sesuai kebutuan pengguna

kosong = {} #base dictionaries yang akan diubah-ubah
print('dictionaries kosong : ',kosong)

print("")

#Penambahan data pada base dictionaries yang telah diberikan diawal
#penambahan data menggunakan format : nama dictionaries [data utama]= data sekunder
kosong[0]="Ayu"
kosong[2]= 'Hera'
kosong[3]= 27

#pencetakan base dictionaries yang telah ditambahakan elemen didalamnya
print('Dictionarise kosong yang telah ditambahkan elemen didalamnya :', kosong)

print("")

#Penambahan List pada dictionaries yang diolah 
#pertama akan dideklarasikan list data yang akan ditambahkan
#dengan format : nama dictionaries [nama list/data utama]= list
kosong["List"] = 22,8,54,10

#pencetakan dictionaries yang telah di tambahkan data list didalamnya.
print('Dictionaries yang telah ditambahkan elemen list didalamnnya : ',kosong)

print("")

#Penambahan dictionaries kedalam sebuah dictionaries menjadi sebuah dictionaries 2 dimensi
#dengan format : nama dictionaries [data utama]={dictionaries}
kosong[5]= {"Lambang":{1:"Beta", 2:"Theta", 3:"Delta"}}

#pencetakan dictionaries 2 dimensi.
print('dictionaries yang ditambahkan dictionaries didalamnya : ',kosong)

print("")

#Pada dictionaries kita juga dapat mengubah sebuah data yang telah diinput dan dijalankan di awal
#dengan format : nama dictionaries [nama data utama]= data sekunder yang ingin diubah
kosong[2]="Herayanti"

#pncetakan output hasil pengubahan data.
print('dictionaries yang data sekundernya telah diganti akan menjadi : ',kosong)

dictionaries kosong :  {}

Dictionarise kosong yang telah ditambahkan elemen didalamnya : {0: 'Ayu', 2: 'Hera', 3: 27}

Dictionaries yang telah ditambahkan elemen list didalamnnya :  {0: 'Ayu', 2: 'Hera', 3: 27, 'List': (22, 8, 54, 10)}

dictionaries yang ditambahkan dictionaries didalamnya :  {0: 'Ayu', 2: 'Hera', 3: 27, 'List': (22, 8, 54, 10), 5: {'Lambang': {1: 'Beta', 2: 'Theta', 3: 'Delta'}}}

dictionaries yang data sekundernya telah diganti akan menjadi :  {0: 'Ayu', 2: 'Herayanti', 3: 27, 'List': (22, 8, 54, 10), 5: {'Lambang': {1: 'Beta', 2: 'Theta', 3: 'Delta'}}}


In [51]:
#LATIHAN 5 

#Pencarian salah satu data pada dictionaries yang mengandung banyak anggota didalmnya
#terkessan sulit jika harus mencari satu persatu, maka dapat digunkan beberapa kode untuk memudahkan pengerjaan

#pertama dilakukan pendeklarasian dictionaries
data_2dimensi =  {"Jurusan":"Matematika", "Fakultas":"MIPA","Universitas":"Udayana",
             "Lambang":{1:"Beta", 2:"Theta", 3:"Delta"}}

#Penggunakan kode "get" untuk pencarian
#dengan format : print(nama dictionaries.get(data utama yang ingin dicari))
print('pencarian data menggunakan kode get: ')

print(data_2dimensi.get("MIPA"))
#jika yang dimasukan pada kolom pencarian ialah data sekunder maka output yang akan dikeluarkan berupa "none"
#karena tak ada data utama yang bernama seperti itu

print(data_2dimensi.get("Jurusan"))
#tetap jika yang dimasukkan sebuah data utama maka yang akan keluar adalah data sekundernya.

print('')

#Penggunaan data utama langsung untuk mencari
#dengan format : print(nama dictionaries[data utama])
print('Berikut contoh jika langsung menggunakan data utama : ')
print(data_2dimensi["Lambang"])

pencarian data menggunakan kode get: 
None
Matematika

Berikut contoh jika langsung menggunakan data utama : 
{1: 'Beta', 2: 'Theta', 3: 'Delta'}


In [54]:
#LATIHAN 6

#Latihan ini menjelaskan mengenai data pada dictionaries yang dapat dihapus
#kode penghapusan menggunakan format : det(nama dictionaries[data utama])

#dilakukannya pendeklarasian dictionaries
dic_campuran = {0: 'Ayu', 2: 'Herayanti', 3: 27, 'List': (22, 8, 54, 10), 5: {'Lambang': {1: 'Beta', 2: 'Theta', 3: 'Delta'}}}

print('dictionaries sebelum salah satunya dihapus : ', dic_campuran)

print('')

#kode penghapusan dimasukkan
del(dic_campuran[5])

#dicetaknya dictionaries yang salah satu datanya telah dihapus
print('dictionaries setelah salah satu datanya dihapus : ')
print(dic_campuran)

dictionaries sebelum salah satunya dihapus :  {0: 'Ayu', 2: 'Herayanti', 3: 27, 'List': (22, 8, 54, 10), 5: {'Lambang': {1: 'Beta', 2: 'Theta', 3: 'Delta'}}}

dictionaries setelah salah satu datanya dihapus : 
{0: 'Ayu', 2: 'Herayanti', 3: 27, 'List': (22, 8, 54, 10)}


# 5.19 FUNGSI DALAM PYTHON
Fungsi adalah blok kode yang hanya berjalan saat dipanggil. Pengguna dapat meneruskan data, yang dikenal sebagai parameter, ke dalam suatu fungsi. Suatu fungsi dapat mengembalikan data sebagai hasilnya.

In [61]:
#LATIHAN 1 

#berikut kita akan mengenal kode def dimana kode ini berfungsi untuk mendeklarasikan sebuah fungsi
#format pendeklarasian adalah : def nama fungsi(nilai yang akan diproses):
#seperti pendeklarasian fungsi dibawah ini 

def jargon():
    print('Matematika menyenangkan bukan?')
    
    
#setelah dilakukan pendeklarasian selanjutnya akan dilakukan pemanggilan
#pemanggilan merupakan cara untuk menggunakan kode fungsi yang telah dideklarasikan

print('output fungsi setelah dilakukan pemanggilan : ') 
jargon()

output fungsi setelah dilakukan pemanggilan : 
Matematika menyenangkan bukan?


## 5.19.1 Tugas Fungsi Pada Python

In [70]:
#LATIHAN 2 

#sebuah kode fungsi juga dapat dijalankan jika terdapat 2 nilai yang dimasukkan pada pendeklarasian
def Penjumlahan (bil1,bil2):
    Jumlah = bil1 + bil2
    print('Hasil penjumlahan : ', Jumlah)
    
#setelah dideklarasikan fungsinya maka dapat dilakukan pemanggilan terhadap fungsi tersebut
Penjumlahan(27,8)
#maka akan keluar output berupa hasil penjumlahan

Hasil penjumlahan :  35


In [74]:
#LATIHAN 3

#jika pada latihan 2 menggunakan perintah print, pada latihan ini akan ditambahkan menggunakan perintah return
 
def Penjumlahan (bil1,bil2):
    Jumlah = bil1 + bil2
    return Jumlah
    
#setelah dideklarasikan fungsinya maka dapat dilakukan pemanggilan terhadap fungsi tersebut
hasil = Penjumlahan(27,8)
print('Hasil penjumlahan : ', hasil)
#maka akan keluar output berupa hasil penjumlahan
#pada kode return ini cukup rumit pada pendeklarasian karena harus menginisialkan variabel baru

Hasil penjumlahan :  35


In [77]:
#LATIHAN 4 

#berikut contoh lain dari fungsi menggunakan kode return

#pendeklarasian fungsi
def perkalian(x):
    return 5 * x

#setelah itu dilakukan pemanggilan untuk menjalankan fungsi diatas.
print(perkalian(3))
print(perkalian(5))
print(perkalian(12))

15
25
60


# 5.20 NUMPY
NumPy (Numerical Python) adalah pustaka Python open source yang digunakan di hampir setiap bidang sains dan teknik. Ini adalah standar universal untuk bekerja dengan data numerik di Python, dan merupakan inti dari ekosistem ilmiah Python dan PyData.

## 5.20.1 Perintah Dasar Pada Numpy
Perintah dasar numpy seperti memanggil, menghitung index serta mengetahui dimensinya.

In [85]:
#LATIHAN 1

#format pembuatan numpy ialah : nama numpy= np.bentuk data yg diinginkan(data yng akan di proses)

#Numpy dimana data didalamnya bertipe list biasa

list_sederhana = np.array([2,4,6,8,10])
print(list_sederhana)

print('')

#Numpy dengan data 2 dimensi
#ketika data yang diinput dua dimensi maka output yang dikeluarkan adalah berupa susunan 2 data

data_2dimensi = np.array([[10,12,14,16], [18,20,22,24]])
print(data_2dimensi)

print('')

#Numpy yang mangandung lebih dari 2 list

banyak_data= np.array([[[0,2,4,6],[8,10,12,14]],[[16,18,20,22],[24,26,28,30]], [[32,34,36,38],[40,42,44,46]]])
print(banyak_data)

#outut yang akan dikluarkan berupa matriks untuk setiap listnya.

[ 2  4  6  8 10]

[[10 12 14 16]
 [18 20 22 24]]

[[[ 0  2  4  6]
  [ 8 10 12 14]]

 [[16 18 20 22]
  [24 26 28 30]]

 [[32 34 36 38]
  [40 42 44 46]]]


In [96]:
#LATIHAN 2

#kode perintah ndim bertujuan menghitung banyaknya list yang ada pada sebuah kode numpy
list_sederhana.ndim

1

In [97]:
data_2dimensi.ndim

2

In [98]:
banyak_data.ndim

3

In [99]:
#sedangkan pada kode shape bertujuan menghitung kolom, baris, serta list yang ada pada sebuah numpy

list_sederhana.shape

(5,)

In [100]:
data_2dimensi.shape

(2, 4)

In [101]:
banyak_data.shape

(3, 2, 4)

## 5.20.2 Memanggil Anggota, Kolom, Dan Baris Dengan Numpy

In [93]:
#LATIHAN 3

#Jika ingin memanggil salah satu anggota pada numpy dapat menggunakan kode ini
#dengan format : nama numpy[urutan baris, urutan kolom]

#pertama dilakukan pendeklarasian data numpy
data_2dimensi = np.array([[10,12,14,16], [18,20,22,24]])


print(data_2dimensi) 

#setelah itu dapat dilakukan pemanggilan satu anggota dengan kode
data_2dimensi[1,2]

#setelah dijalankan dapat kita lihat outputnya akan berupa sebuah anggota.

[[10 12 14 16]
 [18 20 22 24]]


22

In [94]:
#jika pada contoh sebelumnya dilakukan pencetakan 1 anggota 
#sekaran dilakukan pencetakan satu baris anggota 
#dengan format : nama numpy[nomor baris,:]

data_2dimensi[1,:]
#maka output yang akan dikeluarkan ialah seluruh anggota pada baris 1

array([18, 20, 22, 24])

In [95]:
#pada contoh ini akan mencetak angota-anggota yang ada pada kolom yang diinginkan
#dengan format kode : nama numpy[:,nomor kolom]

data_2dimensi[:,1]
#output yang akan dikeluarkan ialah anggota anggota yang ada pada kolom 1

array([12, 20])

In [106]:
#pada contoh ini akan mencetak data dengan baris, kolom dan list
data_2dimensi[0,2:3]

array([14])

In [107]:
data_2dimensi[1,1:2:3]

array([20])

In [109]:
#LATIHAN 4

#ada juga kode penggantian data pada numpy
#dijalankan dengan format kode : nama numpy[baris,kolom] = data pengganti

data_2dimensi[1,2]= 33
print('data setelah diganti: ')
print(data_2dimensi)

data setelah diganti: 
[[10 12 14 16]
 [18 20 33 24]]


## 5.20.3 Matriks Pada Numpy

In [110]:
#LATIHAN 5 

np.ones((6,3))

#kode ini berfungsi untuk mencetak sebuah data yaitu data 1 menjadi sebuah matriks pengulangan
#dimana akan diulang sebanyak 6 baris dan 3 kolom
#dengan format : np.ones((baris,kolom))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [112]:
#tak hanya data 1 tapi juga dapat dicetak data 0 menjadi sebuah matriks pengulangan

np.zeros((3,4,2))

#data 0 akan dicetak menjadi 3 matris yang berisikan 4 baris dan 2 kolom

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [113]:
#jika data yang ingin dicetak secara berulan bukanlah 1 atau 0 maka dapet menggunakan kode dibawah ini

np.full((2,4),8)

#maka output yang akan dikeluarkan berupa matriks pengulangan angka 8 
#dalam 2 baris dimana masing masing baris berisikan 4 kolom

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [115]:
np.random.rand(5,2)

#jika kode diatas ini adalah kode dimana datanya ditentukan oleh sistem 
#dikarenakan kita menginput kata random yang berarti bebas sebanyak 5 baris dan masing-masing 2 kolom

array([[0.69493027, 0.22818233],
       [0.3273321 , 0.57397941],
       [0.05596303, 0.65131328],
       [0.49370136, 0.05810356],
       [0.2283854 , 0.01642847]])

In [116]:
np.random.randint(5,25 , size=(9,3))

#sedangkan pada kode ini sistem akan diperintahkan memilih datanya secara sebarang
#namun diberikan batas dalam pemilihan 
#dan akan dibuat sebuah matrik dengan 9 baris 3 kolom pada setiap baris

array([[20,  8, 16],
       [16, 23, 21],
       [16,  8, 12],
       [21, 11, 21],
       [12,  9, 21],
       [ 7, 11,  9],
       [15, 20, 13],
       [ 6, 15,  6],
       [ 5, 13,  9]])

In [117]:
#ada juga pembuatan matriks identitas seperi dibawah ini

identitas = np.identity(4)  #Angka 4 disini menunjukan ordo yang akan dicetak yaitu 4x4

print('Matriks identitas dengan ordo 4x4 :')
print(identitas)

Matriks identitas dengan ordo 4x4 :
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 5.20.4 Copy Pada Numpy

In [118]:
#LATIHAN 6

#pendeklarasian data numpy
List_sederhana = np.array([2,3,5,7,9])
print(List_sederhana)

[2 3 5 7 9]


In [119]:
numpy_sederhana = List_sederhana
print(numpy_sederhana)

#karnadiawal telah dideklarasikan bahwa numpy sederhana sama dengan list sederhana
#maka itu berarti isi nya pun sama

[2 3 5 7 9]


In [121]:
#numpy a =numpy b
#jadi jika salah satu anggota pada numpy b diubah maka numpy a juga ikut terubah

numpy_sederhana[3]=1
print ('berikut numpy b yang telah dirubah :', numpy_sederhana)

print('')

print('dan ini adalah numpy a yang ikut terubah: ',List_sederhana)

berikut numpy b yang telah dirubah : [2 3 5 1 9]

dan ini adalah numpy a yang ikut terubah:  [2 3 5 1 9]


In [122]:
numpy_copy=numpy_sederhana.copy()
print('numpy hasil copy : ',numpy_copy)

#diatas adalah contoh kode jika ingin men-copy sebuah numpy
#menjadi numpy yang memiliki nama yang berbeda.

numpy hasil copy :  [2 3 5 1 9]


In [124]:
#jika ingin mengubah numpy yang telah dicopy tidak akan merubah numpy asal
numpy_copy[3]=0

print('hasil numpy yg dicopy lalu diubah :', numpy_copy)

print('')

print('numpy asal : ',numpy_sederhana)
#output numpy asal akan tetap sama seperti awal

hasil numpy yg dicopy lalu diubah : [2 3 5 0 9]

numpy asal :  [2 3 5 1 9]


## 5.20.5 Operasi Matematika Pada Numpy

In [130]:
#LATIHAN 7

#pertama dilakukan pendeklarasian numpy
numpy_asal = np.array([2,3,5,1,9])

#operasi penjumlahan
numpy_asal+2
#pada operasi ini semua data pada numpy akan ditambah 2

array([ 4,  5,  7,  3, 11])

In [132]:
#operasi perkalian 
numpy_asal*3
#pada operasi ini setiap data pada numpy akan dikalikan 3 begitu seterusnya untuk oprasi yang lainnya

array([ 6,  9, 15,  3, 27])

In [133]:
numpy_lawan = np.array([12,13,14,15,16])

In [135]:
#operasi numpy 1 dengan numpy yg lainnya
numpy_asal+numpy_lawan
#maka setiap data pada numpy akan saling dioperasikann sesuai dengan urutan mereka.
#hal ini berlaku juga terhadap semua tanda operasi matematika.

array([14, 16, 19, 16, 25])

In [136]:
#operasi cos
np.cos(numpy_asal)
#maka akan di operasikan semua data dengan cos, hal ini juga berlaku pada sin, tan, sinh, cosh, tanh, sqrt

array([-0.41614684, -0.9899925 ,  0.28366219,  0.54030231, -0.91113026])

## 5.20.6  Perkalian Matriks Pada Numpy

In [137]:
#kali ini ada operasi perkalian matriks 
#pada operasi perkalian ini membutuhkan numpy 2 dimensi

numpy_asal = np.array([[0,2,4,6],[10,12,14,16]])
print(numpy_asal)

[[ 0  2  4  6]
 [10 12 14 16]]


In [138]:
numpy_lawan = np.array([[18,20,22,24], [26,28,30,32]])
print(numpy_lawan)

[[18 20 22 24]
 [26 28 30 32]]


In [139]:
hasil_kali = numpy_asal*numpy_lawan
print(hasil_kali)
#perkalian matrik pada numpy akan merhasil jika sama sama memiliki ordo yang sama

[[  0  40  88 144]
 [260 336 420 512]]


In [141]:
numpy_lain = np.array([[2,4],[6,8],[10,12],[14,16]])
print(numpy_lain)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [142]:
x = np.matmul(numpy_asal,numpy_lain)
print(x)

[[136 160]
 [456 560]]


## 5.20.7 Min, Max, Dan Sum Pada Numpy

In [143]:
numpy_a = np.array([[0,2,4,6],
              [10,12,14,16],
              [18,20,22,24]])
print(numpy_a)

[[ 0  2  4  6]
 [10 12 14 16]
 [18 20 22 24]]


In [146]:
numpy_b = np.min(numpy_a)
print(numpy_b)

0


In [147]:
numpy_c = np.min(numpy_a,axis =0)
print (numpy_c)
#baris terkecil

[0 2 4 6]


In [148]:
numpy_d = np.min(numpy_a,axis =1)
print(numpy_d)
#pencarian kolom terkecil

[ 0 10 18]


In [149]:
numpy_e = np.max(numpy_a)
print(numpy_e)
#nilai maksimal dari numpy a

24


In [151]:
numpy_f = np.max(numpy_a,axis=0)
print(numpy_f)
#ini adalah baris terbesar

[18 20 22 24]


In [152]:
numpy_g = np.max(numpy_a,axis=1)
print(numpy_g)
#ini adalah kolom terbesar

[ 6 16 24]


In [153]:
numpy_h = np.sum(numpy_a)
print (numpy_h)

148


In [155]:
numpy_h = np.sum(numpy_a,axis=0)
print (numpy_h)

[28 34 40 46]


In [156]:
numpy_i = np.sum(numpy_a,axis=1)
print (numpy_i)

[12 52 84]
